services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog-service:
    build:
      context: .             
      dockerfile: app/Dockerfile
    container_name: catalog-app
    ports:
      - "5001:5001"
    restart: always

  cart-service:
    build:
      context: .              
      dockerfile: cart/Dockerfile
    container_name: cart-app
    ports:
      - "5002:5002"
    environment:
      - CATALOG_BASE_URL=http://catalog-service:5001 
      - RABBITMQ_HOST=rabbitmq
      - ORDER_SERVICE_URL=http://order-service:3000
    depends_on:
      - catalog-service
      - rabbitmq
      - order-service

  order-service:
    build:
      context: .             
      dockerfile: orders/Dockerfile
    container_name: order-app
    ports:
      - "8080:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy