name: CICD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          [ -f app/requirements.txt ] && pip install -r app/requirements.txt || echo "app/req not found"
          [ -f cart/requirements.txt ] && pip install -r cart/requirements.txt || echo "cart/req not found"
          [ -f orders/requirements.txt ] && pip install -r orders/requirements.txt || echo "orders/req not found"

      - name: Test Build and Run with Docker Compose
        run: |
          docker compose build
          docker compose up -d
          sleep 15
          docker compose ps

      - name: Run All Tests (Unit, Integration, E2E)
        run: |
          python -m pytest tests/ -v -s

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push Catalog Image
        uses: docker/build-push-action@v5
        with:
          context: .                
          file: ./app/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/catalog-service:latest

      - name: Push Cart Image
        uses: docker/build-push-action@v5
        with:
          context: .                  
          file: ./cart/Dockerfile     
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cart-service:latest

      - name: Push Orders Image
        uses: docker/build-push-action@v5
        with:
          context: .                  
          file: ./orders/Dockerfile   
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest